### ISSUE TITLE
【建议】邮箱输入能否也自动记录词库

### ISSUE THREAD

**Issue by a810439322** [gaboolic/rime-frost#100]
1. 从搜狗过来的，希望@也可以触发邮箱后缀的候选，很方便
2. 比如输入abcdefg@foxmail.com，每次都要拼一遍，希望输入几次以后也能被记录进词库里

**Comment by gaboolic** [comment]
触发后缀的候选是可以实现的，比如弄个置顶短语，
加上
@       @126.com
@       @qq.com
再把@放到字母表就行了
不过这样的话，@就不能直接打出了，在群里艾特别人的时候不方便了

至于“输入[abcdefg@foxmail.com](mailto:abcdefg@foxmail.com)，每次都要拼一遍” 也可以用置顶短语来实现，比如
gerenziliao       abcdefg@foxmail.com
