### ISSUE TITLE
更新到e51e0a6b717810678f787e3732954c00ade9ee23后，无法使用以词定字

### ISSUE THREAD

**Issue by MerFrederick** [gaboolic/rime-frost#101]
恢复到dcaf7ac5cd210f61431e0aaac00783522fd76d97没有此问题

**Comment by gaboolic** [comment]
试试最新版
之前删除了rime.lua 漏了一处改动
`- lua_processor@*select_character          # 以词定字`

**Comment by MerFrederick** [comment]
> 试试最新版 之前删除了rime.lua 漏了一处改动 `- lua_processor@*select_character # 以词定字`

最新版已解决，谢谢
