### ISSUE TITLE
方案选择

### ISSUE THREAD

**Issue by Unsung-dev** [gaboolic/rime-frost#102]
<img width="551" alt="image" src="https://github.com/user-attachments/assets/c042e30c-f09f-4eee-8e44-4c33bf042331">
<img width="472" alt="image" src="https://github.com/user-attachments/assets/bebdda85-a413-4d96-ad2b-3c6d4b9530fb">

我刚才git pull出错，就重新安装了一遍，输入法方案也没有双拼了？也没有白霜拼音？

**Comment by gaboolic** [comment]
看上去是你的用户路径里没有此仓库配置？
朙月拼音是官方自带的 如果啥都没有 就是朙月拼音

**Comment by Unsung-dev** [comment]
那我需要怎么操作？
现在很难用

**Comment by gaboolic** [comment]
检查下用户文件夹，是否有此仓库的配置

**Comment by Unsung-dev** [comment]
![CleanShot 2024-12-04 at 11 19 24@2x](https://github.com/user-attachments/assets/4756f72d-b1e3-4d50-b33c-c66d58336523)
看一下

**Comment by gaboolic** [comment]
那就是你没有选中
用【小狼毫】输入法设定，选中一下

**Comment by Unsung-dev** [comment]
好了，我忘了重新部署了，谢谢
