### ISSUE TITLE
请问如果希望从雾凇拼音迁移，需要做什么工作呢？

### ISSUE THREAD

**Issue by chlorine3545** [gaboolic/rime-frost#106]
如题，使用雾凇拼音有一段时间了，现在希望试一试白霜。因为目前已经积累了一些用户数据，不希望丢失。请问如果希望做到尽量无缝的迁移，需要做什么工作呢？多谢指点！

**Comment by gaboolic** [comment]
先备份好之前的配置
然后导出用户词典
再试试切换配置，导入用户词典？

**Comment by chlorine3545** [comment]
> 先备份好之前的配置 然后导出用户词典 再试试切换配置，导入用户词典？

目前大概的步骤应该是：

- 备份原本的配置文件夹
- 导入 rime-frost 的源代码
- 导入自定义词典、各种 `.custom.yaml` 和 `custom_phrase.txt`
- 挂载自定义词典
- 将 `rime_ice.userdb` 重命名为 `rime_frost.userdb`
- 重新部署

如果自定义更多，可能需要更多步骤。

**Comment by gaboolic** [comment]
我突然想到  你把白霜词库文件复制过去用也是可以的……
