### ISSUE TITLE
RIME+白霜词库可否实现自动记忆输入过的英文单词？

### ISSUE THREAD

**Issue by GRDpengyuyan** [gaboolic/rime-frost#111]
目前主力使用rime+白霜词库双拼一段时间了，感觉越来越顺手了。但是，好像输入法不会记录输入过的但是不包含在英文词库的单词，比如一些英文缩写或者专有名词。这个是设置问题吗，我也自己搜索过，有网友表示单纯依赖rime输入法本身实现不了这个功能。

**Comment by gaboolic** [comment]
打开英文词库的用户词典的话，单词上屏可以自动记忆
但是问题是不在用户词典的好像打不出来吧？打不出来 就记忆不了，死锁了

**Comment by gaboolic** [comment]
你试试把a-z 26个字母也加到主词库里面
