### ISSUE TITLE
为何放入文件夹后，输入法没有出现

### ISSUE THREAD

**Issue by linonetwo** [gaboolic/rime-frost#112]
![图片](https://github.com/user-attachments/assets/f06d928f-ed54-4942-b2ae-dfc5d012ec0d)

**Comment by gaboolic** [comment]
好像是因为多套了一层
把里面的东西直接放到这个文件夹

**Comment by linonetwo** [comment]
![图片](https://github.com/user-attachments/assets/2b111684-5b1d-4e87-8a94-cb0aa0aba408)

直接丢进去就有了，就是文件夹变得比较乱，哈哈，谢了。
