### ISSUE TITLE
squirrel.yaml怎么删除了？

### ISSUE THREAD

**Issue by weiminghaoo** [gaboolic/rime-frost#117]
squirrel.yaml怎么删除了？

**Comment by gaboolic** [comment]
之前就改了下皮肤，后来发现随着鼠须管更新 squirrel.yaml的内容也会变
干脆取消了，不改squirrel.yaml了

**Comment by weiminghaoo** [comment]
> 之前就改了下皮肤，后来发现随着鼠须管更新 squirrel.yaml的内容也会变 干脆取消了，不改squirrel.yaml了

那mac端的配置 ，应该在哪里配置😂,我现在是把之前的配置文件拿过来了
<img width="307" alt="image" src="https://github.com/user-attachments/assets/4e2d8f4d-6791-4da8-a6b0-714145e0180e" />

**Comment by gsgqgyq** [comment]
我是直接用之前的 `squirrel.custom.yaml`，没有任何影响。

**Comment by weiminghaoo** [comment]
> 我是直接用之前自定义的 `squirrel.custom.yaml`，没有任何影响。

用`squirrel.custom.yaml`没法关闭所有的app_options😥

**Comment by noisay** [comment]
> 之前就改了下皮肤，后来发现随着鼠须管更新 squirrel.yaml的内容也会变 干脆取消了，不改squirrel.yaml了

皮肤也可以设置在对应的custom文件中，不管鼠须管如何更新，就都不影响了

**Comment by gaboolic** [comment]
> > 之前就改了下皮肤，后来发现随着鼠须管更新 squirrel.yaml的内容也会变 干脆取消了，不改squirrel.yaml了
> 
> 皮肤也可以设置在对应的custom文件中，不管鼠须管如何更新，就都不影响了

嗯，皮肤留给用户自己定义了😂

**Comment by gaboolic** [comment]
> > 我是直接用之前自定义的 `squirrel.custom.yaml`，没有任何影响。
> 
> 用`squirrel.custom.yaml`没法关闭所有的app_options😥

你可以自己从squirrel文件夹复制出来 squirrel.yaml改

**Comment by weiminghaoo** [comment]
> > > 我是直接用之前自定义的 `squirrel.custom.yaml`，没有任何影响。
> > 
> > 
> > 用`squirrel.custom.yaml`没法关闭所有的app_options😥
> 
> 你可以自己从squirrel文件夹复制出来 squirrel.yaml改

我现在就这么做的，麻烦把`squirrel.yaml`放到`.gitignore`吧

**Comment by Kelfvin** [comment]
所以应该如何做？

**Comment by weiminghaoo** [comment]
> 所以应该如何做？

从历史版本中拿出来
