### ISSUE TITLE
iOS 仓输入法如何导入白霜词库

### ISSUE THREAD

**Issue by suesai** [gaboolic/rime-frost#118]
按照readme里面的指导，仓输入法里面没有找到白霜词库，请问该怎么手动导入呢？或者说覆盖哪些文件呢？

**Comment by gaboolic** [comment]
我记得仓里面有白霜的

**Comment by suesai** [comment]
![image](https://github.com/user-attachments/assets/0c2dbb27-de98-4213-8419-2ca5a5733270)
![image](https://github.com/user-attachments/assets/30479eab-0ae0-4ce4-a575-f4db0e2bad75)
![image](https://github.com/user-attachments/assets/186bd9ea-186c-461e-9f68-245fe4f824b3)
一共就这些，没有找到白霜

**Comment by gaboolic** [comment]
墨奇白霜拼音

**Comment by suesai** [comment]
感谢😆
