### ISSUE TITLE
候选字上方的*号是什么功能？

### ISSUE THREAD

**Issue by chwt163** [gaboolic/rime-frost#12]
如图，有的候选有，有的又没有，这个是白霜词库的功能还是rime的功能？
![Screenshot_20240723_110151_info plateaukao einkbro_edit_960042308259751](https://github.com/user-attachments/assets/26cb0900-cf35-4edf-a15e-386609bb5b26)

**Comment by freeorca** [comment]
是白霜的功能。用户词典的词加*号。是靠lua文件夹里的“is_in_user_dict.lua”实现的。这个文件实现三个功能：用户词典的词加星号，用户置顶的词加闪电图标，整句联想的词加𑄗符号。如果你只需要部分功能，可以把不要的段落注释掉。
![图片](https://github.com/user-attachments/assets/76f83974-5396-4208-8068-3e48a88594fb)
<br>
如果三个功能都不需要，可以不启用这个lua文件，在“rime_frost.schema.yaml”里把这个滤镜注释掉。
![图片](https://github.com/user-attachments/assets/48ae0cce-4e2e-49c5-8504-ab4be438cc41)

**Comment by gaboolic** [comment]
如楼上所言，是lua实现的
*表示这个词是在用户词典里的词

**Comment by chwt163** [comment]
明白了，谢谢！

**Comment by chwt163** [comment]
明白了，谢谢！
