### ISSUE TITLE
请问候选词右上角的*代表什么？

### ISSUE THREAD

**Issue by Thinkbond** [gaboolic/rime-frost#13]
刚才雾凇切换过来，发现很多候选词右上角都会显示“*”，有的还会有方块，如下图所示，望解惑，谢谢！
![image](https://github.com/user-attachments/assets/add2058e-7eb3-476b-b25f-4b3ad7520b31)

**Comment by Thinkbond** [comment]
补充一下，正常打表情是能正常显示的。
![image](https://github.com/user-attachments/assets/e3548455-660e-4675-93b9-c8785e4048c9)

**Comment by Thinkbond** [comment]
才发现前面已经有人问过了。

**Comment by gaboolic** [comment]
方块好像是 躺着的8？ 是表示这个词/句不在词库里 自动根据词频生成的

**Comment by freeorca** [comment]
方块大概是作者大大说的躺着的8，就是𑄗这个符号？我把这个符号拷到word里，设了好几种常用的字体去显示，都没法显示出来，要么是个方块，要么就是完全不显示。但是我自己win10上的白霜，打字的时候是可以显示出来的，也不知道最终是fallback到哪个字体上去把它给显示出来的。楼主如果系统各个字体都没有这个符号，可能就只能显示方块了。
![图片](https://github.com/user-attachments/assets/85930c65-e755-404d-906e-2586f27376da)
<br>
我自己是嫌它太大了，和首页效果图不一致（大概和显示这个符号的字体有关？），改了个小点的符号“∞”
![图片](https://github.com/user-attachments/assets/5940657f-f7d7-4cc0-96c0-5ee2eb0254ce)

**Comment by gaboolic** [comment]
> 方块大概是作者大大说的躺着的8，就是𑄗这个符号？我把这个符号拷到word里，设了好几种常用的字体去显示，都没法显示出来，要么是个方块，要么就是完全不显示。但是我自己win10上的白霜，打字的时候是可以显示出来的，也不知道最终是fallback到哪个字体上去把它给显示出来的。楼主如果系统各个字体都没有这个符号，可能就只能显示方块了。 ![图片](https://private-user-images.githubusercontent.com/36132130/351597136-85930c65-e755-404d-906e-2586f27376da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDg3MDYsIm5iZiI6MTcyMTgwODQwNiwicGF0aCI6Ii8zNjEzMjEzMC8zNTE1OTcxMzYtODU5MzBjNjUtZTc1NS00MDRkLTkwNmUtMjU4NmYyNzM3NmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA4MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNzEzODRlMWM0MzI4MzUzYzY1NGY3M2RkYjExNTNjYjU0ZWJlMDRkNWY1NGQwMzFhNzc3NWNkMTY3MmUxMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jgl7zNwUhTGDww6UfuWY2AfpNRdebpqYCG1UuwI5Yaw) 我自己是嫌它太大了，和首页效果图不一致（大概和显示这个符号的字体有关？），改了个小点的符号“∞” ![图片](https://private-user-images.githubusercontent.com/36132130/351597552-5940657f-f7d7-4cc0-96c0-5ee2eb0254ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDg3MDYsIm5iZiI6MTcyMTgwODQwNiwicGF0aCI6Ii8zNjEzMjEzMC8zNTE1OTc1NTItNTk0MDY1N2YtZjdkNy00Y2MwLTk2YzAtNWVlMmViMDI1NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA4MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMWIzZDU0MTQ1OTY0NTVmMTYyMjAxYzU2MjM5MDdjMzczZTQxMGQwZDE5ZmEyNDE1MzgxNzBiNjZjYzk2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3HUxVZvxdsfrsKZVUxLBNxta-vgnpMhhEQQvjrTcVE4)

∞ 不错 我后面也改成∞吧
