### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by zhl111** [gaboolic/rime-frost#14]
是否我把生成的fcitx5的词库txt文件，导入fcitx5后，就不需要再把‘source-code.zip’导入到’/Android/data/org.fcitx.fcitx5.android/files/data/rime‘里了？这两是一回事吗？

**Comment by gaboolic** [comment]
生成的fcitx5的词库txt文件，导入fcitx5后，是可以用fcitx5自带的拼音的，不需要rime，这个和rime没关系
不是一回事
使用rime的话 就是把整个文件夹压缩包 放到’/Android/data/org.fcitx.fcitx5.android/files/data/rime‘里

**Comment by gaboolic** [comment]
可以的 rime直接用源代码就行 others可以删掉 是一些脚本 不删也行
