### ISSUE TITLE
候选项数字标号会无故消失

### ISSUE THREAD

**Issue by AmenLi** [gaboolic/rime-frost#17]
如图，候选字的数字标号会消失
错误时候表现：![PixPin_2024-08-02_00-37-00](https://github.com/user-attachments/assets/2811b5a7-e405-43df-b876-eaa3ccc6ccde)
出现问题时候按数字也能正常上屏，但就是不显示数字

正常表现：
![PixPin_2024-08-02_16-29-00](https://github.com/user-attachments/assets/84ae76ea-108f-42c1-9ab2-1a40cc25fb82)

复现方法：无法稳定复现，它是随机出现的，有可能我打上一个字时候，数字标号还在，下一个字的候选框里就突然没有数字标号

暂时的修复方法：退出算法服务，删除配置文件夹里的build文件夹里所有文件，重启算法服务，重新部署两次，才能恢复正常。
或者重启电脑一次。

我无法确定是词库方案的问题还是weasel的问题还是rime的问题，所以先来这边问问。
网上也没搜到类似的。搜索相关配置“ label_format: "%s" ”暂时也没搜到解决方法

weasel版本是0.16.1，目前用的是白霜词库0.0.3，之前用雾凇拼音的方案时也会出现一样问题
我目前自己自定义修改的地方如下：
[https://gist.github.com/AmenLi/59dab0cc71b0d983821d1fc0d84b7e9a](https://gist.github.com/AmenLi/59dab0cc71b0d983821d1fc0d84b7e9a)

**Comment by gaboolic** [comment]
那你可能得去weasel问问
