### ISSUE TITLE
大佬，frost_dict_for_fcitx5.txt文件怎么使用啊

### ISSUE THREAD

**Issue by villyjack** [gaboolic/rime-frost#18]
新人小白，下载frost_dict_for_fcitx5.txt后不知道如何使用，请大佬百忙之中指点一下，谢谢🙏🙏🙏

**Comment by gaboolic** [comment]
fcitx5输入法导入词库用的，和rime没关系
用rime的话直接整个配置复制过去就行了

**Comment by villyjack** [comment]
> fcitx5输入法导入词库用的，和rime没关系 用rime的话直接整个配置复制过去就行了

好的，谢谢
