### ISSUE TITLE
皮肤配置文件有重复

### ISSUE THREAD

**Issue by mzhnuaa** [gaboolic/rime-frost#21]
皮肤配置文件有重复，请删除重复配置

**Comment by gaboolic** [comment]
squirrel.yaml文件吗？是哪里

**Comment by mzhnuaa** [comment]
> squirrel.yaml文件吗？是哪里

是的，例如solarized_rock solarized_dark这些自带的主题，重名

**Comment by gaboolic** [comment]
修改了
