### ISSUE TITLE
词库如何导入

### ISSUE THREAD

**Issue by fufumo** [gaboolic/rime-frost#31]
![Clip_2024-08-24_15-41-58](https://github.com/user-attachments/assets/9b5ed007-1996-40f6-aa43-c10608a9aacc)
![Clip_2024-08-24_15-42-19](https://github.com/user-attachments/assets/f6c066c8-e89d-4a2e-a54b-009feabca29a)
默默点了个星为什么这么好的词库星这么少
我的问题是我从搜狗转过来的 然后我想把我们的一些专业名词导入进去，我直接把搜狗词库使用转换工具转成yaml,我找了一晚上找不到我的词库应该放在哪里（不咋会使用rime），并且我发现我输入datetime他不会出日期，是因为什么功能没开吗

今天早上我找到了这个文件，我把我的词库放进去了，但是他似乎没读取到，是因为权重太低了吗，转换工具转换后的权重好像是越小越常用
求解

**Comment by gaboolic** [comment]
我试了下 datetime现在会出日期呀
转换工具转换后的权重 数字越大 越靠前

**Comment by gaboolic** [comment]
搜狗词库 可以用深蓝转换 你放的位置是对的

**Comment by fufumo** [comment]
> 搜狗词库 可以用深蓝转换 你放的位置是对的

可以了 ，我直接导入的词库，然后使用云输入就好多了

**Comment by fufumo** [comment]
> 搜狗词库 可以用深蓝转换 你放的位置是对的

可以了 ，我直接导入的词库，然后使用云输入就好多了

**Comment by LDM-2833** [comment]
就着这个问题展开问下，想要挂载多个场景的词库，好方便开启和关闭。所以说想在用户根目录下建一个个人词库的文件夹，如果全都添导入白霜词库方案的tables，这个文件夹的词库会被挂载识别出来吗?
