### ISSUE TITLE
符号/fh

### ISSUE THREAD

**Issue by gbsix** [gaboolic/rime-frost#34]
rime和rime-frost都是下载的最新的， 安装后输入/fh，/xl都没有出现符号，是什么原因呢？ 谢谢

**Comment by gaboolic** [comment]
/fh
©®℗℠™

/xl
αβγδ

我试了下，这两个都是有的

**Comment by cool-delete** [comment]
> /fh ©®℗℠™
> 
> /xl αβγδ
> 
> 我试了下，这两个都是有的

![image](https://github.com/user-attachments/assets/ce9c1d93-e191-4dc7-a185-aab122f3b3ae)
