### ISSUE TITLE
刚接触 rime ，竖排选词是怎么弄的

### ISSUE THREAD

**Issue by yiteei** [gaboolic/rime-frost#37]
![chrome_0sNvSvqo0y](https://github.com/user-attachments/assets/ff429d81-9cc5-49bd-b156-7026b44d73bf)
![image](https://github.com/user-attachments/assets/89aecd81-6271-4744-adfa-ebff28042356)
Windows 11

**Comment by Ipseamor** [comment]
在文件weasel.yaml中，type: vertical   这行前面的#去掉

**Comment by gaboolic** [comment]
可以 看小狼毫的更新日志

https://rime.im/release/weasel/

新增參數 style/text_orientation: "horizontal" | "vertical", 與 style/vertical_text: bool 冗餘，設定文字繪製方向，兼容 squirrel 參數

**Comment by yiteei** [comment]
> 在文件weasel.yaml中，type: vertical 这行前面的#去掉

谢谢
