### ISSUE TITLE
如何让pin_cand_filter中置顶的词 也显示'⚡️'

### ISSUE THREAD

**Issue by changzaicl** [gaboolic/rime-frost#38]
lua_filter@is_in_user_dict  开启后，可以出现∞、*标记，在custom_phrase中的，也可以出现⚡️。
请问这个这个如何使用在pin_cand_filter中置顶的词也显示⚡️。

谢谢！

**Comment by gaboolic** [comment]
那应该要修改pin_cand_filter这个lua，把置顶的词的comment加上⚡️

**Comment by changzaicl** [comment]
在您的is_in_user_dict.lua中是如下写的，我在想pin_cand_filter.lua中是cand.type == 哪一类。
请问您能帮助简单修改一下吗？谢谢！

        -- 用户词库，加上*号
        if cand.type == "user_phrase" then
            cand.comment = '*'
        end
        -- 用户置顶词
        -- if cand.type == "user_table" then
        --     cand.comment = cand.comment .. '⚡️'
        -- end

        -- 整句联想，加上𑄗符号
        if cand.type == 'sentence' then
            cand.comment = '∞'
