### ISSUE TITLE
[提问] 与上游雾凇拼音的同步频率？

### ISSUE THREAD

**Issue by EtaoinWu** [gaboolic/rime-frost#4]
README 中写道当前版本的白霜基于雾凇的 [af2480b](https://github.com/iDvel/rime-ice/commit/af2480ba1b147a6a54c0c21e2997ef451c34e036) commit。考虑到雾凇更新较勤，请问白霜项目是否有计划周期性从雾凇中同步词库更新？

**Comment by gaboolic** [comment]
不会再同步了 重制了

**Comment by gaboolic** [comment]
后面可能会从搜狗细胞词库 弄点词。但是现在的词 大部分都全了

**Comment by gaboolic** [comment]
后面会用一些新词发现算法，以及周期从搜狗提供的词库、维基百科来发现新词

**Comment by plutotree** [comment]
感觉挺可惜的，现在能持续更新的词表越来就少，有没有可能合作共建，共同维护，双向同步  

这里@下雾凇作者

**Comment by gaboolic** [comment]
> 感觉挺可惜的，现在能持续更新的词表越来就少，有没有可能合作共建，共同维护，双向同步
> 
> 这里@下雾凇作者

雾凇拼音的更新频率现在很低了 你可以看看commit 十天半个月基本上也没有几个新增的词
https://github.com/iDvel/rime-ice/issues/666 这里提交的人也很少了（以前我提的多）
目前白霜的词 我使用新词发现 已经增添了上万个新词汇了 比雾凇的全

**Comment by gaboolic** [comment]
雾凇不是上游 算是init吧
