### ISSUE TITLE
请问备选词某些词后面会出现的符号是什么意思？

### ISSUE THREAD

**Issue by LukNg** [gaboolic/rime-frost#48]
有些词后面会有星号*，有些词后面会有无限符号，都是什么意思呀？

**Comment by LukNg** [comment]
还有一些比较生僻的字（类似“喰”），输入can找不到这个字，只能通过部首拆字打出来，这种问题应该怎么解决呢？

**Comment by djy112230** [comment]
> 有些词后面会有星号*，有些词后面会有无限符号，都是什么意思呀？

这个好像是自己词库的词语和那个什么联想机制的词库就有符号，也想问一下，怎么取消这些符号呢

**Comment by changzaicl** [comment]
https://github.com/gaboolic/rime-frost/blob/master/lua/is_in_user_dict.lua
修改这里，可以得到自己喜爱的符号。
不想显示，在 rime_frost.schema.yaml中注释掉此行即可。 
# filters:
    - lua_filter@*is_in_user_dict # 用户词典的词加上一个*

**Comment by djy112230** [comment]
> https://github.com/gaboolic/rime-frost/blob/master/lua/is_in_user_dict.lua 修改这里，可以得到自己喜爱的符号。 不想显示，在 rime_frost.schema.yaml中注释掉此行即可。
> 
> ```
>  # filters:
>     - lua_filter@*is_in_user_dict # 用户词典的词加上一个*
> ```
大佬，还是不行啊，注释掉rime_frost.schema.yaml的
 # filters:
    - lua_filter@*is_in_user_dict # 用户词典的词加上一个*
按照这个格式注释掉，那个*号和无限符号还是存在呢
如果注释掉https://github.com/gaboolic/rime-frost/blob/master/lua/is_in_user_dict.lua里面符号管理那几行，就不能打字了

**Comment by gaboolic** [comment]
```
---
name: rime_frost
version: "2023-11-13"
import_tables:
  - cn_dicts/8105     # 字表
  # - cn_dicts/41448  # 大字表（按需启用）
```
找到rime_frost.dict.yaml，把# - cn_dicts/41448  # 大字表（按需启用）前面的# 去掉，注意-要和上面的-对齐
这样就打开了4万个汉字
这种“喰”生僻字 可以打 can`k   出来，`后可以加辅助码，这个是“口”字旁就是k

**Comment by gaboolic** [comment]
有些词后面会有星号*，有些词后面会有无限符号
楼上说的对，不想要的话可以把- lua_filter@*is_in_user_dict去掉

**Comment by djy112230** [comment]
> 有些词后面会有星号*，有些词后面会有无限符号 楼上说的对，不想要的话可以把- lua_filter@*is_in_user_dict去掉

- lua_filter@*is_in_user_dict注释掉或者删掉这一行没有用啊，还是有*和无限符号

**Comment by gaboolic** [comment]
改完重新部署了吗 改的文件是你用的方案吗

**Comment by djy112230** [comment]
> 改完重新部署了吗 改的文件是你用的方案吗

搞定了，谢谢大哥
