### ISSUE TITLE
在开启lua_filter@*aux_code的情况下完全无内容显示

### ISSUE THREAD

**Issue by liuyifan-eric** [gaboolic/rime-frost#49]
前端是macos的squirrel，具体表现为，输入任何内容后完全没有可选项显示
<img width="138" alt="image" src="https://github.com/user-attachments/assets/ff1e2960-0a50-4a75-a281-e127321a1f02">
切换至其他输入方案（IPA、雾凇）则可以正常输入，依赖于白霜的几个双拼也有同样问题

rime_frost.schema.yaml第83行(engine/filters:)
`- lua_filter@*aux_code                 # 墨奇辅助码`
将其替换为雾凇拼音对应schema中
`- lua_filter@search@radical_pinyin              # 部件拆字辅码`
则问题解决

是通过plum安装的，相关文件应该都已经是最新版
```
$bash rime-install gaboolic/rime-frost:others/recipes/full
Installing for Rime frontend: rime/squirrel
Updating package: gaboolic/rime-frost
Already up to date.
Installing recipe: gaboolic/rime-frost:others/recipes/full
No files updated.
```

完整rime配置文件夹如下（去除了build、cn_dicts、cn_dicts_cell以满足文件大小限制）
[Rime.bak3.zip](https://github.com/user-attachments/files/17003736/Rime.bak3.zip)

**Comment by gaboolic** [comment]
![QQ_1726357547817](https://github.com/user-attachments/assets/1a1c5893-5bfa-4050-bba9-94f25450a85d)

**Comment by gaboolic** [comment]
![QQ_1726357575628](https://github.com/user-attachments/assets/8de5d247-de85-499d-a7f9-0861cdf117d7)

**Comment by gaboolic** [comment]
我是直接下载的github的源码zip，是可以的
可能是plum少文件了 我下次修下

**Comment by gaboolic** [comment]
好像是少了aux_code文件夹 我刚在plum配方加了一行
你再测试下？

**Comment by liuyifan-eric** [comment]
> 好像是少了aux_code文件夹 我刚在plum配方加了一行
> 
> 你再测试下？

应该是的了，我还特地看了下lua里没缺少aux_code，原来是少了个文件夹
