### ISSUE TITLE
能请大佬在包里加个一键执行的配置更新文件吗？

### ISSUE THREAD

**Issue by djy112230** [gaboolic/rime-frost#50]
在 Rime 文件夹执行 git pull 即可。

Mac: cd ~/Library/Rime && git pull
Windows: cd "$env:APPDATA\Rime" && git pull
其他系统以此类推

非程序员的小白，这段看不懂，能请大佬能在包里加个一键执行的文件吗~

**Comment by gaboolic** [comment]
一键 可以装官方的plum (东风破）
https://github.com/gaboolic/rime-frost?tab=readme-ov-file#%E9%80%9A%E8%BF%87-%E4%B8%9C%E9%A3%8E%E7%A0%B4-%E5%AE%89%E8%A3%85

然后你弄个.bat文件 里面写 `bash rime-install gaboolic/rime-frost:others/recipes/full` 就是一键

**Comment by gaboolic** [comment]
东风破 https://github.com/rime/plum

**Comment by gaboolic** [comment]
因为rime是跨平台的，写个通用脚本一键执行 不太现实
windows下 像我说的那样可以
