### ISSUE TITLE
请问cn_dicts_cell内的词库也要全部添加是吧

### ISSUE THREAD

**Issue by Anber55** [gaboolic/rime-frost#58]
你好，之前一直使用的雾凇词库，想改用白霜，但是除了cn_dicts内的词库是需要必须用的，请问cn_dicts_cell内的词库是额外选用还是得全部都用才能达到选词最优化，谢谢

**Comment by gaboolic** [comment]
不用细胞词库也可以
细胞词库是锦上添花，只开启你需要的即可，例如 历史 音乐什么的

**Comment by Anber55** [comment]
好的，感谢
