### ISSUE TITLE
辅助码 日期与时间dt 的時區

### ISSUE THREAD

**Issue by leojlhsieh** [gaboolic/rime-frost#60]
謝謝作者，很好用的輸入法！

我在歐洲瑞士，當我使用辅助码 日期与时间 dt，時區會有誤，但日期時間正確。
例如：
- 正確應是 2024-10-02T14:26:53+02:00
- dt得到是 2024-10-02T14:26:53+08:00

**Comment by gaboolic** [comment]
Lua 的标准库并没有直接提供获取时区信息的功能，目前是在/lua/date_translator.lua写死的

-- ISO 8601/RFC 3339 的时间格式 （固定东八区）（示例 2022-01-07T20:42:51+08:00）
    elseif (input == M.datetime) then
        local current_time = os.time()
        yield_cand(seg, os.date('%Y-%m-%dT%H:%M:%S+08:00', current_time))
        yield_cand(seg, os.date('%Y-%m-%d %H:%M:%S', current_time))
        yield_cand(seg, os.date('%Y%m%d%H%M%S', current_time))

**Comment by leojlhsieh** [comment]
原來如此 Thanks!
