### ISSUE TITLE
建议readme的安装说明细化补充一下

### ISSUE THREAD

**Issue by maturethan** [gaboolic/rime-frost#65]
首先非常感谢大佬做这么好用的词库。可以说开箱即用且易用性非常高

然后就是建议readme的安装说明细化补充一下，装完rime、复制完白霜文件后
还要去输入法设定里选择白霜拼音才是真正启用

我一直以为复制完就可以了，折腾很久词库都用不起来。毕竟用户有我这样的非程序员普通人
我是别人直接推荐rime+白霜来的，没有任何前置知识储备

因此建议大佬readme可以考虑多写一步，包到上车

最后再次感谢大佬，祝大佬薪水节节攀升

**Comment by gaboolic** [comment]
好的

**Comment by gaboolic** [comment]
加上了
