### ISSUE TITLE
拆字

### ISSUE THREAD

**Issue by samuelwander** [gaboolic/rime-frost#67]
大佬，您好。我是新手，研究了好一会儿，不知道怎么拆字反查，还是白霜目前没有加入这个功能啊？

**Comment by Haclankid** [comment]
输入`uU`后再开始输入你需要拆的字，例如`众`：`uUrenrenren`。

**Comment by samuelwander** [comment]
> > 大佬，您好。我是新手，研究了好一会儿，不知道怎么拆字反查，还是白霜目前没有加入这个功能啊？
> 
> 输入`uU`后再开始输入你需要拆的字，例如`众`：`uUrenrenren`。

还是不懂，大佬。就是每次打uU的话，就切到字母了，如果是uu的话，后面接着输入都变成字母了，不会体现拆字这个。

**Comment by samuelwander** [comment]
> > 大佬，您好。我是新手，研究了好一会儿，不知道怎么拆字反查，还是白霜目前没有加入这个功能啊？
> 
> 输入`uU`后再开始输入你需要拆的字，例如`众`：`uUrenrenren`。

谢谢大佬，已经解决了，经过群里别人指导发现需要按着shift键输入才行，才明白。

**Comment by gaboolic** [comment]
是的 感谢大家回复
