### ISSUE TITLE
能否让单字不置顶

### ISSUE THREAD

**Issue by Twilight-9** [gaboolic/rime-frost#68]
能否让打单字不置顶？每打一个单词似乎都加入了用户词典。

**Comment by gaboolic** [comment]
你好 可以修改的

**Comment by QuantumRoseinAmethystVase** [comment]
我试了很久还是不知道配置在哪

**Comment by gaboolic** [comment]
你是想 不修改单字的频率吗？
这个可以改disable_user_dict_for_patterns: 禁止某些编码录入用户词典

**Comment by Twilight-9** [comment]
> 你是想 不修改单字的频率吗？ 这个可以改disable_user_dict_for_patterns: 禁止某些编码录入用户词典

成功了

**Comment by Twilight-9** [comment]
分享我的解决方案。

自己用的方案加补丁：
```
patch：
  translator/disable_user_dict_for_patterns:
    - "^.{1,2}$"  # 禁用任意长度为1或2的字符串的用户词典
```

即可实现单字不加入用户词典
