### ISSUE TITLE
计算器功能引导导致表情不能上屏

### ISSUE THREAD

**Issue by showyourlucky** [gaboolic/rime-frost#70]
输入 [V表情] 后, 按数字小键盘选择表情不能上屏
![image](https://github.com/user-attachments/assets/f6d79eba-8cff-4f26-a2ba-bf8a61ffd0ff)

建议修改正则如下, 计算器以V+数字触发
recognizer:
  patterns:
  calculator: "^V\\\\d+.*$"                 #计算器功能引导

**Comment by gaboolic** [comment]
计算器有可能字母开头，比如  开头sqrt(10)
