### ISSUE TITLE
关于上屏造词与词频

### ISSUE THREAD

**Issue by dgjisi** [gaboolic/rime-frost#73]
感谢辛苦制作

请问一下该如何设备上屏造词与已上屏的词自动靠前调整词频

**Comment by gaboolic** [comment]
应该是能自动调频的 打的多了就靠前了

**Comment by dgjisi** [comment]
谢谢回复，能否看一下，下面这几个参数放进去并没有生效，需要如果设置呢

  enable_sentence: true                # 句子输入模式
  enable_user_dict: true               # 是否开启用户词典（用户词典记录动态字词频，用户词）
  enable_encoder: true                  # 自动造词
  encode_commit_history: true          # 是否对已上屏的词自动造词

**Comment by gaboolic** [comment]
找到对应的地方加进去就可以了
enable_user_dict: true  现在应该就是true，自动调频的
