### ISSUE TITLE
关于rime_frost.txt文件

### ISSUE THREAD

**Issue by c02y** [gaboolic/rime-frost#75]
rime_frost.txt是rime-frost自动生成的文件，主要记录的是我们自己选择的词汇，就是候选词里面带星号的那些

问题是rime_frost.txt文件并没有放到.gitignore里面

我是从rime-ice转过来的，rime-ice对应的文件是rime_ice_private.txt文件, 有一个rime_ice_private.dict.yaml文件用于修改rime_ice.dict.yaml文件的，比如禁用或者开启一些词典什么的

rime-frost没有沿用rime-ice这部分，我能够在rime-frost下面使用rime_frost_private.dict.yaml，但是发现rime_frost.txt并不在.gitignore里面，里面倒是有个`*private*`，所以解决方法有两个
1. 将rime_frost.txt改名为rime_frost_private.txt, 和rime-ice类似
2. 将rime_frost.txt加到.gitignore里面去

**Comment by Cruise888** [comment]
个人感觉老哥说的这个功能用得比较少吧，不过有解决办法还是很赞👍

**Comment by Cruise888** [comment]
如果自选词出错或错别字了，可以在这个文件内改正或删除吧。

**Comment by Cruise888** [comment]
没有找到rime_frost.txt这个文件，需要自己创建么？还是…

**Comment by c02y** [comment]
> 个人感觉老哥说的这个功能用得比较少吧，不过有解决办法还是很赞👍

这个是用来备份用的，类似于Linux下面的dotfiles



> 如果自选词出错或错别字了，可以在这个文件内改正或删除吧。

据我所知不行，你得在输入法里面删除，比如打出来，输入法候选词里面使用Ctrl-Delete删除，否则sync一下就会把旧文件的内容覆盖掉rime_frost.txt文件



> 没有找到rime_frost.txt这个文件，需要自己创建么？还是…

部署一下就出现了，默认除了几行注释基本是空的

**Comment by gaboolic** [comment]
我看了下 我没有特殊设置user_dict相关的东西
这样的话 默认出来的应该是rime_frost.userdb （我这鼠须管确实出现的也是rime_frost.userdb）
*.userdb/  现在是忽略的
rime_frost.txt我也不知道怎么来的

**Comment by c02y** [comment]
> 我看了下 我没有特殊设置user_dict相关的东西 这样的话 默认出来的应该是rime_frost.userdb （我这鼠须管确实出现的也是rime_frost.userdb） *.userdb/ 现在是忽略的 rime_frost.txt我也不知道怎么来的 我这没出现，按默认的配置应该不会有的，我记得要把用户词典的格式改成txt才会出现

rime_frost.txt是我打patch修改配置之后Deploy生成的
```
# double_pinyin_flypy.custom.yaml
patch:
  translator/+:
    db_class: tabledb
```

详情请看：https://github.com/iDvel/rime-ice/issues/363
