### ISSUE TITLE
关于双拼模式下的英文词库

### ISSUE THREAD

**Issue by e-chehil** [gaboolic/rime-frost#79]
我新增了一种双拼方案，但是发现在未输入完全时，很容易出现大量的英文备选。

![图片](https://github.com/user-attachments/assets/6f56ad52-6a59-4793-b8f9-fb6fa0789497)

而默认的几个双拼方案中则不会有这种情况，输入单个字母不会显示英文。

![图片](https://github.com/user-attachments/assets/2e0a28ad-2f4c-463c-ba19-a04a5bfa5b6d)

检查了很久，不知道哪里没配置好，melt_eng.schema.yaml 和 radical_pinyin.schema.yaml 都有修改，但还是没能解决。

**Comment by Ipseamor** [comment]
新增的双拼方案中，英文输入方案中的  enable_completion:ture 改成false

**Comment by Ipseamor** [comment]
新增的双拼方案中，英文输入方案中的  enable_completion:ture 改成false
