### ISSUE TITLE
纠错能力有待加强

### ISSUE THREAD

**Issue by veizei-K** [gaboolic/rime-frost#80]
有时候输入拼音顺序错误，搜狗可以纠正，但是白霜无法纠正过来
![PixPin_2024-11-05_10-27-33](https://github.com/user-attachments/assets/9806aa6e-89b6-41f8-930d-e30693c5077a)
![PixPin_2024-11-05_10-28-00](https://github.com/user-attachments/assets/25d378ac-7bb8-4c5c-83ac-026e81eaab30)

**Comment by gaboolic** [comment]
rime需要自定义纠错，纠错这一点上比不上商业输入法
我觉得纠错不是刚需，纠错多了形成错误的肌肉记忆了，会一直打错，不利于提速
