### ISSUE TITLE
Arch AUR庫的安裝存在自衝突且不可用

### ISSUE THREAD

**Issue by stephenjkhsieh** [gaboolic/rime-frost#81]
在Arch用AUR安裝 `rime-frost-git` 時，有依賴包 `librime` 。但是 `librime` 中的 `rime-luna-pinyin` 又與 `rime-frost-git` 衝突。希望有辦法做成不會衝突，以實現多輸入法並存（rime-frost以git安裝時，這點是可以辦到的）。
即便把 `rime-luna-pinyin` 刪除解決衝突，部署rime時會顯示Rime has encountered an error. See log for details. ，無法使用。

**Comment by gaboolic** [comment]
看这里，https://github.com/gaboolic/rime-frost/issues/69

可以在https://aur.archlinux.org/packages/rime-frost-git 讨论下
