### ISSUE TITLE
数字大写R、农历N、计算器V如何操作

### ISSUE THREAD

**Issue by e-chehil** [gaboolic/rime-frost#83]
按下大写按键会进入英文输入，不知道如何使用这些功能。

windows 10
weasel-0.16.3.0

**Comment by gaboolic** [comment]
shift+R
按住shift

**Comment by cool-delete** [comment]
> shift+R 按住shift

输入shiftR 写阿拉伯数字的时候候选区出现大写
但是shiftV 怎么操作啊 接33在候选区第二位置出现33=33 如果我输入+ 不参与计算啊?

**Comment by nevertoday** [comment]
我也不知道怎么调出来这个农历日期
