### ISSUE TITLE
cn_dicts 这个词库, 每个词条都含拼音编码, rime引擎不是会自动计算编码吗, 为什么要包含呢?

### ISSUE THREAD

**Issue by xxxdo1** [gaboolic/rime-frost#85]
cn_dicts 这个词库, 每个词条都含拼音编码, rime引擎不是会自动计算编码吗, 为什么要包含呢?

**Comment by gaboolic** [comment]
多音字计算的不对
比如 棋差一着 qi cha yi zhao
不注音，自动计算的是qi cha yi zhe

**Comment by xxxdo1** [comment]
懂了
