### ISSUE TITLE
如何让单字不加入用户词库rime_frost.txt

### ISSUE THREAD

**Issue by c02y** [gaboolic/rime-frost#87]
现在很多单字都会写入到rime_frost.txt文件，导致很多时候打字的时候候选列表一堆单字都有星号，有无办法配置一下让单字禁止加入到用户词库rime_frost.txt

下面的命令行可以列出文件内第一列也就是第一行只包含一个字母或者一个汉字的所有行看能不能受此启发加入到代码里面去
```
gawk --re-interval '$1 ~ /^([a-zA-Z0-9\u4E00-\u9FFF\u3040-\u30FF])$/ { print }' rime_frost.txt
```

**Comment by gaboolic** [comment]
有个配置项：
disable_user_dict_for_patterns: 禁止某些编码录入用户词典

**Comment by Twilight-9** [comment]
same#68

**Comment by c02y** [comment]
> 有个配置项： disable_user_dict_for_patterns: 禁止某些编码录入用户词典

您好，可不可以具体说说，如何禁止单字，我全局搜了一下github，自己也试了一下，貌似都不行

**Comment by Twilight-9** [comment]
> > 有个配置项： disable_user_dict_for_patterns: 禁止某些编码录入用户词典
> 
> 您好，可不可以具体说说，如何禁止单字，我全局搜了一下github，自己也试了一下，貌似都不行

方案加补丁：
```
patch：
  translator/disable_user_dict_for_patterns:
    - "^.{1,2}$"  # 禁用任意长度为1或2的字符串的用户词典
```

**Comment by c02y** [comment]
> - "^.{1,2}$"  # 禁用任意长度为1或2的字符串的用户词典

多谢，不过我试了一下，比如我打“wo”，选择“沃”，虽然我只打“wo”的时候“沃”不会标星号（不加上述配置则会有星号），但是“women”的时候，下面的“沃”还是会被标星号，因为“沃”已经被加入了用户词典，Reploy一下全新的rime_frost.txt文件会有新增的“沃”单字

**Comment by Twilight-9** [comment]
> > * "^.{1,2}$"  # 禁用任意长度为1或2的字符串的用户词典
> 
> 多谢，不过我试了一下，比如我打“wo”，选择“沃”，虽然我只打“wo”的时候“沃”不会标星号（不加上述配置则会有星号），但是“women”的时候，下面的“沃”还是会被标星号，因为“沃”已经被加入了用户词典，Deploy一下全新的rime_frost.txt文件会有新增的“沃”单字

看了rime/librime，disable_user_dict_for_patterns应该是在某些编码下禁止使用/加载用户词典，并不是禁止这些编码加入用户词典。我再想想其他办法。

**Comment by Twilight-9** [comment]
我怀疑究竟有没有“禁止某些编码加入用户词典”的功能

**Comment by gaboolic** [comment]
rime应该只有disable_user_dict_for_patterns  这个功能
