### ISSUE TITLE
MacOS v 模式无法触发, 候选词没有符号

### ISSUE THREAD

**Issue by custsly** [gaboolic/rime-frost#90]
输入法状态是中文, 英文标点, vfh 无法触发 v 模式
但是如果把输入法标点修改为中文标点, 使用 /fh 正常能用
<img width="871" alt="image" src="https://github.com/user-attachments/assets/142ec1e0-bcdd-4ef5-bfde-fec9a745c008">
<img width="238" alt="image" src="https://github.com/user-attachments/assets/ef9ddbe4-38a6-43c5-ac86-7cea12c5c0eb">

**Comment by custsly** [comment]
知道原因了, 提了 pr https://github.com/gaboolic/rime-frost/pull/91

**Comment by gaboolic** [comment]
使用/触发的
/fh
