### ISSUE TITLE
在Ubuntu 22.04下默认配置完打字没有候选框

### ISSUE THREAD

**Issue by wenduof** [gaboolic/rime-frost#92]
打字没有候选框，无法使用
默认配置，即 1. git clone 2. deploy

有候选框的情况，如图
![Screenshot from 2024-11-20 19-43-38](https://github.com/user-attachments/assets/fd3a59d9-e9cf-42db-bf3e-a8ca70c310bf)

**Comment by gaboolic** [comment]
https://github.com/rime/home/discussions/1493

**Comment by wenduof** [comment]
> 可能ubuntu22自带的版本太低了 试试用flatpck版本的fcitx5吧 https://flathub.org/zh-Hans/apps/org.fcitx.Fcitx5 我用的这个

rime-ice是可以的，不知能否单纯通过配置的方式解决？感谢

**Comment by gaboolic** [comment]
主要是我不知道问题出在哪里了，理论上说都是rime配置，没有区别

**Comment by gaboolic** [comment]
你看下rime的日志 有没有报错呢

**Comment by wenduof** [comment]
[I1125 15:24:08.996654 2667 engine.log](https://github.com/user-attachments/files/17898996/I1125.15.24.08.996654.2667.engine.log)

**Comment by gaboolic** [comment]
好像是有个错误
E1125 15:24:38.852198  2667 lua_gears.cc:15] LuaTranslation::Next error(2): [string "table.unpack = table.unpack or unpack..."]:4: attempt to call a nil value (upvalue 'f')
但是看不出来是哪里

**Comment by gaboolic** [comment]
我记得Ubuntu 22.04里的rime不光是lua有问题，词频都有问题
比如你打“ai”  的时候，第一位 应该不是爱 哎  唉 挨 那些吧，我记得第一位会出现 皑什么的 都是不常用字，不按方案里设置的词频走

**Comment by wenduof** [comment]
![Screenshot from 2024-11-25 15-38-50](https://github.com/user-attachments/assets/36cb815d-6f14-42a7-b6c9-b537a2504482)
我是双拼

**Comment by gaboolic** [comment]
你试试用flatpck版本的最新的fcitx5 看看有没有问题

**Comment by xiefenchao-x** [comment]
请问问题解决了吗，我也遇到了同样的问题

**Comment by xiefenchao-x** [comment]
https://www.mintimate.cc/zh/guide/faQ.html#linux%E8%96%84%E8%8D%B7%E9%85%8D%E7%BD%AE%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8

**Comment by xiefenchao-x** [comment]
[解决方案](https://www.mintimate.cc/zh/guide/faQ.html#linux%E8%96%84%E8%8D%B7%E9%85%8D%E7%BD%AE%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8)

**Comment by wenduof** [comment]
> 请问问题解决了吗，我也遇到了同样的问题

还没，使用ice-rime最新版没问题，所以不应该是依赖库版本问题我猜
升级新版librime我还没试，主要顾虑部署以后万一不行影响现有工作，我得找到一台适合的机器

**Comment by gaboolic** [comment]
老版本的lua插件依赖rime.lua，现在的配置文件里已经没有 rime.lua了，可能是这个原因
手动升级或编译librime对普通用户比较复杂，我的建议就是用和我一样用最新的flatpck版本的fcitx5，这个不受发行版的打包版本限制 能用到最新的东西

**Comment by wenduof** [comment]
ibus版本用这个可以解决问题
https://github.com/hchunhui/ibus-rime.AppImage
