### ISSUE TITLE
双拼方案可以加入模糊音设置吗

### ISSUE THREAD

**Issue by xw-INIT** [gaboolic/rime-frost#98]
双拼方案可以加入模糊音设置吗，我自己在小鹤双拼的配置中加入了模糊音设置上，但是不生效

**Comment by gaboolic** [comment]
理论上是可以的，双拼和模糊音都是对全拼的改写，
你看看改写顺序？

**Comment by nevertoday** [comment]
确实这个模糊音，我也没有找到设置的地方

**Comment by xw-INIT** [comment]
> 确实这个模糊音，我也没有找到设置的地方

我也忘记了在哪个文件里面修改，但是我刚刚看了一眼，在rime_frost.schema.yaml这个文件和你使用的双拼对应的那个文件里面都修改了模糊音设置，然后现在就可以用了
    - derive/eng$/en/
    - derive/en$/eng/
    - derive/in$/ing/
    - derive/ing$/in/
    - derive/uan$/uang/
    - derive/uang$/uan/
    - derive/^([^aeou]?h?)ang$/$1an/
    - derive/^([^aeou]?h?)an$/$1ang/
这个是我现在用的模糊音设置，可以实现en和eng，in和ing，uan和uang，an和ang的转换，ian和iang因为区别明显，所以我没有设置模糊音，如果这个也需要的话，把最后两项的[^aeou]改成[^aeoui]就可以了
