### ISSUE TITLE
【提问】请问设置了默认标点，。为,.  要什么快捷键才可以切换回来呢

### ISSUE THREAD

**Issue by a810439322** [gaboolic/rime-frost#99]
程序员工作中用到的英文标点比较多，但也有用中文标点的需求呢，刚接触Rime不久，求大佬解答

**Comment by gaboolic** [comment]
你怎么设置的 就在哪设置回来
默认就是中文下中文标点，英文下英文标点，你不去改就行了

**Comment by a810439322** [comment]
> 你怎么设置的 就在哪设置回来 默认应该是ctrl+`打开菜单 默认就是中文下中文标点，英文下英文标点，你不去改就行了

我想表达的是，中文下英文标点，这个需求是在的，但是设置以后，在需要用中文标点的时候不能很灵活的切换过来，缺少一个快捷键切换中英文标点，可能是我不会设置吧~

**Comment by gaboolic** [comment]
这个你可以自己改快捷键的
现在有快捷键 你看default.yaml
```
    - { when: always, toggle: ascii_punct, accept: Control+Shift+3 }              # 切换中英标点
    - { when: always, toggle: ascii_punct, accept: Control+Shift+numbersign }     # 切换中英标点
```
